#!/bin/env expect
#
#
# this is the main script for the DENX Universal Test System (DUTS)
#
# TODO add (c) etc.
#
#
#

set BASE_DIR "./"
set verbose "no"
set debugging "yes"

##
## include global defines
##
source "$BASE_DIR/include/defs.tcl"

##
## include helper procedures
##
source "$BASE_DIR/include/utils.tcl"
source "$BASE_DIR/include/dev.tcl"
source "$BASE_DIR/include/ui.tcl"
source "$BASE_DIR/include/tc.tcl"
source "$BASE_DIR/include/config.tcl"

##
## initialise vars to default values
##
set argc [llength $argv]

# working directory, may be overwritten with user-supplied -d option
set DEFAULT_DIR "testsystems/dulg"
if {[in_array env DUTS_DIR]} {
	if { $env(DUTS_DIR) != "" } {
		set working_dir $env(DUTS_DIR)
	} else {
		set working_dir $DEFAULT_DIR 
	}
} else {
	set working_dir $DEFAULT_DIR
}

# global list of testcases
set l_testcases [list]

# associative array for internal representation of all test cases
array set a_testcases ""

# current test case 
set cur_tc ""


# global list of test groups
set l_testgroups [list]

array set a_testgroups ""


# global list of selected test cases to execute
set l_runlist [list]

# global list of supported target boards
set l_boards [list]
array set a_devices ""
set cur_device ""

# board name 
set board_name ""

# global list of defined configuration views
set cur_config ""

set selected_config ""

# current TC context (state)
set cur_context "off"
set dst_context ""


set connected "no"

set powered_on "no"


# default location for log files
set logs_location $LOG_DIR 


set dry_run "no"

# assume we're local to the VL by default
set remote "no"

# spawn id identifiers for console and control connections
set console_con ""
set control_con ""

##
## let's get going...
##
if { $argc == 0 } {
	usage
}

# increase expect's buffer size
match_max 16384

parse_params
exit
