#!/usr/bin/expect
#
# this is the main script for the DENX Universal Test System (DUTS)
#
# 
#

#############################################################################

##
## include global defines
##
source "common/defs.tcl"


##
## initialise vars to default values
##

set argc [llength $argv]

set verbose "no"
set debugging "yes"

# TC descriptions directory - may be overwritten with user-provided '-d'
# option
set tc_dir $TC_DESCR_DIR 

# global list of testcases
set l_testcases [list]

# associative array for internal representation of all test cases
array set a_testcases ""

# current test case 
set cur_tc ""


# global list of test groups
set l_testgroups [list]

array set a_testgroups ""


# global list of selected test cases to execute
set l_runlist [list]

# global list of supported target boards
set l_boards [list]


set connected "no"

# default location for log files
set logs_location $LOG_DIR 


set dry_run "no"


##
## include helper procedures
##
source "common/utils.tcl"
source "common/ui.tcl"


if { $argc == 0 } {
	usage
}


parse_params

exit

