#
#
#

global _context_firmware_prompt

# generate a pseudo number
proc rndom {{limit 65536}} {
	set r [expr int(rand() * $limit)]
	return $r
}

set p [string trimright $_context_firmware_prompt]
set sn [string toupper [format "%x-%x-%x" [rndom] [rndom] [rndom]]]

#puts $sn

#send_user -- "<verbatim>\n"
send_user -- "$p setenv ethaddr !!!!!!FILL_THIS!!!!!!\n"
send_user -- "$p setenv serial# $sn\n"
#send_user -- "</verbatim>\n"

return 1
