#
# 
#

expect "*"

if ![_context_firmware_get_prompt] {
	p_err "could not get firmware prompt"
	return 0
}

send -s "reset\r"

#
# get "Hit any key to stop autoboot"
# key press 
# get prompt
#
expect {
	timeout {
		p_err "timed out while waiting for autoboot prompt"
		return 0
	}
	"Hit any key to stop" {
		send -s "\r"
	}
}

if ![_context_firmware_get_prompt] {
	p_err "could not get firmware prompt after reset"
	return 0
}

return 1
