#
# mtest may take ages so we test for a specific pattern
#
global _context_firmware_prompt TIMEOUT

if ![_context_firmware_get_prompt] {
	p_err "could not get firmware prompt"
	return 0
}

set timeout 600

send -s "mtest 100000 200000\r"
expect "0000000F"
send -s "\003"
expect {
	timeout {
		p_err "timed out while waiting for firmware prompt"
		return 0
	}
	$_context_firmware_prompt
}

set timeout $TIMEOUT
return 1
