#
# 
#

global _context_kernel_prompt cur_context

expect "*"

send -s "run flash_nfs\r"
expect {
	timeout {
		p_err "timed out after 'flash_nfs'" 1
	}
	"Bad Magic Number" {
		p_err "problems finding image?!"
		return
	}
	"Linux version" {
		set cur_context "kernel"
		set timeout 300
		expect "login: "

		set timeout 10
		send -s "root\r"
		expect {
			timeout {
				p_err "timed out while waiting for kernel prompt"
				return
			}
			"$_context_kernel_prompt" {
			}
		}
	}
}
