#
# interactively modify memory and display result
#
global _context_firmware_prompt
expect "*"
if ![_context_firmware_get_prompt] {
	p_err "could not get firmware prompt"
	return 0
}

send -s "nm.b 100000\r"
expect "?"

foreach v {48 65 6c 6c 6f} {
	send -s "$v\r"
	sleep 0.25
	expect "?"
}

send -s ".\r"
expect {
	timeout {
		p_err "timed out while waiting for firmware prompt"
		return 0
	}
	$_context_firmware_prompt
}
unset v

set rv [_context_firmware_command "md 100000 8" ".*"]

return $rv
