#!/bin/bash
#
# (C) Copyright 2006, 2007 Rafal Jaworowski <raj@semihalf.com> for DENX Software Engineering
# (C) Copyright 2008 Detlev Zundel <dzu@denx.de>, DENX Software Engineering
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#
# prepares .log files for use with DULG wiki (adds tags, renames, makes
# tarball)
#
usage () {
    echo "usage: `basename $0` [-v] [boardname]"                                      1>&2
    echo "       All log-files for board with the extension .log will be massaged"    1>&2
    echo "       into .txt files ready for the DULGData_<board> web.  This includes"  1>&2
    echo "       removing CRs and adding <verbatim> and </verbatim> closures."        1>&2
    echo "       The processed files are then tarred up into DULGData_<boardname>.tgz"1>&2
    echo "         -v be verbose about actions"                                       1>&2
    exit 1
}

cleanup() {
    rm -fr $dulgdata
}

# Parse options (bash extension)
while getopts v option
do
    case $option in
	v)	verbose=1
		;;
	*)      usage
		exit 1
		;;
    esac
done
shift $(( $OPTIND - 1 ))

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

if ls ${1}*.log >/dev/null 2>&1; then
    :
else
    echo "No logfiles for $1 found - giving up" 1>&2
    exit 1
fi

dulgdata="DULGData_$1"
if [ -d $dulgdata ]; then
    echo "Directory $dulgdata exists already - giving up" 1>&2
    exit 1
fi

trap cleanup SIGINT
mkdir $dulgdata

done=""
for f in ${1}*.log; do
	n=`echo $f | sed 's/\.log$/\.txt/; s/^'$1'//; s/^_//'`
	[ -n "$verbose" ] && echo "Processing $n"
	( echo "<verbatim>"; sed ' s/\r//g; 1 {/^[ \t]*$/ d};' < $f | col -b ; echo "</verbatim>" ) > ${dulgdata}/$n
	done="$done $n"
done

[ -n "$verbose" ] && echo "Creating ${dulgdata}.tgz"
tar -czf ${dulgdata}.tgz $dulgdata
cleanup
