#!/bin/bash
#
# (C) Copyright 2006, 2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#

#
# prepares .log files for use with DULG wiki (adds tags, renames, makes
# tarball) $1: board name 
#

if test -z "$1"; then
	echo "Missing board name"
	exit 1
fi

for f in `ls`; do n=`echo $f | sed 's/\.log$/\.txt/'`;
	echo "<verbatim>" > $n; cat $f >> $n; echo "</verbatim>" >> $n;
done

tar -cvzf $1_logs.tgz *.txt
